### ISSUE TITLE
Documentation: Write a blog post.

### ISSUE THREAD

**Issue by ghost** [ConsenSys/kubernetes-azure#1]

**Comment by hermanjunge** [comment]
Add this Diagram:

![kubernetes on azure](https://cloud.githubusercontent.com/assets/729830/15272834/456969a2-1a5c-11e6-8248-033963c38f20.png)

**Comment by ghost** [comment]
Add this diagram:

![kubernetes on azure](https://cloud.githubusercontent.com/assets/729830/15291038/7721ceac-1b52-11e6-95ce-52545b7b779b.png)
